server:
  error:
    include-message: always
    include-binding-errors: always

  port: 8001

spring:
  datasource:
    password: Bossstan@1995
    url: jdbc:mysql://localhost:3306/user_registration?useSSL=false&allowPublicKeyRetrieval=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

  mail:
    host: 10.10.0.11
    port: 25
    username: nadmin@kenac.co.zw
    password: Kenac321

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

