server:
  error:
    include-message: always
    include-binding-errors: always

  port: 8001

spring:
  datasource:
    username: username
    password: password
    url: jdbc:mysql://localhost:3306/user_registration?useSSL=false&allowPublicKeyRetrieval=true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

  mail:
    host: mailserver.host
    port: mailserver.portnumber
    username: mailserver.username
    password: mailserver.password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: mailserver.host
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
        transport:
          protocol: smtp




